# Generated by Django 3.1.2 on 2020-10-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sighting_date', models.DateField(blank=True, help_text='Date of squirrel sighting')),
            ],
        ),
    ]
