# Generated by Django 3.1.2 on 2020-10-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0005_auto_20201015_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='sighting_date',
            field=models.DateField(blank=True, help_text='Date of squirrel sighting'),
        ),
    ]
