# Generated by Django 3.1.2 on 2020-10-22 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0007_auto_20201015_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='helper_date',
            field=models.CharField(blank=True, help_text='Helper function', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(blank=True, choices=[('adult', 'adult'), ('juvenile', 'juvenile')], help_text='Squirrel age', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of sighting', validators=[django.core.validators.MinValueValidator(40.7644), django.core.validators.MaxValueValidator(40.8006)]),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of sighting', validators=[django.core.validators.MinValueValidator(-73.9818), django.core.validators.MaxValueValidator(-73.9491)]),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='shift',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='AM or PM', max_length=2),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='sighting_date',
            field=models.DateField(blank=True, help_text='Date of squirrel sighting'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='unique_id',
            field=models.CharField(help_text='Unique sighting id', max_length=100, unique=True),
        ),
    ]
